export const sellerNav = [
  { name: "Dashboard Overview", href: "/seller/dashboard", icon: "LayoutDashboard" },
  { name: "Deposit USDT", href: "/seller/deposit-usdt", icon: "Wallet" },
  { name: "Wallet Balance", href: "/seller/wallet", icon: "Wallet" },
  { name: "Sell USDT", href: "/seller/sell-usdt", icon: "CircleDollarSign" },
  { name: "Withdraw USDT", href: "/seller/withdraw-usdt", icon: "CircleDollarSign" },
  { name: "Active Orders", href: "/seller/active-orders", icon: "ListOrdered" },
  { name: "Order History", href: "/seller/order-history", icon: "History" },
  { name: "Transaction History", href: "/seller/transactions", icon: "CreditCard" },
  { name: "Payment Methods", href: "/seller/payment-methods", icon: "Wallet" },
  { name: "KYC Verification", href: "/seller/kyc", icon: "FileCheck2" },
  { name: "Notifications", href: "/seller/notifications", icon: "Bell" },
  { name: "Support Ticket", href: "/seller/support", icon: "HelpCircle" },
  { name: "Profile & Security", href: "/seller/profile-security", icon: "ShieldCheck" },
  { name: "Referral System", href: "/seller/referrals", icon: "Users" },
];

export const adminNav = [
  { name: "Dashboard Analytics", href: "/admin/dashboard", icon: "LayoutDashboard" },
  { name: "User Management", href: "/admin/users", icon: "Users" },
  { name: "Pending KYC", href: "/admin/kyc", icon: "FileCheck2" },
  { name: "Orders Management", href: "/admin/orders", icon: "ListOrdered" },
  { name: "Wallet Management", href: "/admin/wallets", icon: "Wallet" },
  { name: "Deposit Settings", href: "/admin/deposit-settings", icon: "Wallet" },
  { name: "Payment Methods", href: "/admin/payments", icon: "CreditCard" },
  { name: "Manual Approvals", href: "/admin/approvals", icon: "FileCheck2" },
  { name: "Notifications", href: "/admin/notifications", icon: "Bell" },
  { name: "Support Tickets", href: "/admin/tickets", icon: "HelpCircle" },
  { name: "Reports", href: "/admin/reports", icon: "History" },
  { name: "Revenue Dashboard", href: "/admin/revenue", icon: "CircleDollarSign" },
  { name: "Security Logs", href: "/admin/security-logs", icon: "ShieldCheck" },
  { name: "Roles & Permissions", href: "/admin/roles", icon: "UserCog" },
  { name: "System Settings", href: "/admin/settings", icon: "Settings" },
];
